[tool.poetry]
name = "minecraft-copilot-ml"
version = "0.1.0"
description = ""
authors = ["DemyCode <verycols@gmail.com>"]
readme = "README.md"
packages = [{ include = "minecraft_copilot_ml" }]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.0.1"
torchvision = "^0.15.2"
torchaudio = "^2.0.2"
selenium = "^4.9.1"
nbtschematic = {git = "https://github.com/DemyCode/nbtschematic.git", branch = "master"}
litemapy = {git = "https://github.com/DemyCode/litemapy.git", branch = "master"}
pandas = "^2.0.1"
tqdm = "^4.65.0"
scikit-learn = "^1.2.2"
mlflow = "^2.3.2"
boto3 = "^1.26.146"
boto3-stubs = {extras = ["essential"], version = "^1.26.146"}

[tool.poetry.group.dev.dependencies]
ipympl = "^0.9.3"
pre-commit = "^3.3.2"
black = "^23.3.0"
flake8 = "^6.0.0"
ipykernel = "^6.23.0"
mypy = "^1.3.0"
pytest = "^7.3.1"
matplotlib = "^3.7.1"
pytest-watch = "^4.2.0"
pytest-testmon = "^2.0.8"

[tool.black]
line-length = 120

[tool.mypy]
exclude = ['.venv']
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
